/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dados;

/**
 *
 * @author hugoa
 */
public class Grafica extends javax.swing.JFrame {

    Dado dados=new Dado();
    Jugador jugador=new Jugador();
    public int suma;
    
    
    public Grafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        textoValor2 = new javax.swing.JTextField();
        textoValor1 = new javax.swing.JTextField();
        botonLanzar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textoApuesta = new javax.swing.JTextField();
        textoMensaje = new javax.swing.JTextField();
        textoBilletera = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        textoValor2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textoValor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textoValor1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textoValor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoValor1ActionPerformed(evt);
            }
        });

        botonLanzar.setText("Lanzar");
        botonLanzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLanzarMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apuesta");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mensaje");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Billetera");

        textoApuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoApuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textoMensaje.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        textoMensaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        textoBilletera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoBilletera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoBilletera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoBilleteraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(textoValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(botonLanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textoBilletera, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonLanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoApuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoBilletera, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonLanzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLanzarMouseClicked
        
        dados.lanzar();
        this.textoValor1.setText( String.valueOf(dados.valor1));
        this.textoValor2.setText( String.valueOf(dados.valor2));
        suma=dados.valor1+dados.valor2;
        jugador.apuesta=Float.parseFloat(textoApuesta.getText());
        
        switch (suma){  
            
            case 2:{  
                jugador.billetera=jugador.billetera-jugador.apuesta;
                this.textoMensaje.setText("Lastimosamente perdiste: "+jugador.apuesta);
                this.textoBilletera.setText( String.valueOf(jugador.billetera));
            }break;
            case 3:{  
                jugador.billetera=jugador.billetera-jugador.apuesta*2;
                this.textoMensaje.setText("Lastimosamente perdiste: "+jugador.apuesta*2);
                this.textoBilletera.setText( String.valueOf(jugador.billetera));
            }break;
            case 7:{  
                jugador.billetera=jugador.billetera+jugador.apuesta*2;
                this.textoMensaje.setText("Buena! ganaste: "+jugador.apuesta*2);
                this.textoBilletera.setText( String.valueOf(jugador.billetera));
            }break;
            case 11:{  
                jugador.billetera=jugador.billetera+0;
                this.textoMensaje.setText("No has perdido nada");
                this.textoBilletera.setText( String.valueOf(jugador.billetera));
            }break;
            case 12:{  
                jugador.billetera=jugador.billetera+jugador.apuesta;
                this.textoMensaje.setText("Buena! ganaste: "+jugador.apuesta);
                this.textoBilletera.setText( String.valueOf(jugador.billetera));
            }break;
            case 4:{
                jugador.billetera=jugador.billetera-jugador.apuesta*1.5;
                this.textoMensaje.setText("Lastimosamente perdiste: "+jugador.apuesta*1.5);
                this.textoBilletera.setText( String.valueOf(jugador.billetera));
                
            }break;
            case 5:{
                jugador.billetera=jugador.billetera-jugador.apuesta*1.5;
                this.textoMensaje.setText("Lastimosamente perdiste: "+jugador.apuesta*1.5);
                this.textoBilletera.setText( String.valueOf(jugador.billetera));
                
            }break; 
            case 6:{
                jugador.billetera=jugador.billetera-jugador.apuesta*1.5;
                this.textoMensaje.setText("Lastimosamente perdiste: "+jugador.apuesta*1.5);
                this.textoBilletera.setText( String.valueOf(jugador.billetera));
                
            }break; 
            case 8:{
                jugador.billetera=jugador.billetera-jugador.apuesta*1.5;
                this.textoMensaje.setText("Lastimosamente perdiste: "+jugador.apuesta*1.5);
                this.textoBilletera.setText( String.valueOf(jugador.billetera));
                
            }break;
            case 9:{
                jugador.billetera=jugador.billetera-jugador.apuesta*1.5;
                this.textoMensaje.setText("Lastimosamente perdiste: "+jugador.apuesta*1.5);
                this.textoBilletera.setText( String.valueOf(jugador.billetera));
                
            }break;
            default:{
                jugador.billetera=jugador.billetera-jugador.apuesta*1.5;
                this.textoMensaje.setText("Lastimosamente perdiste: "+jugador.apuesta*1.5);
                this.textoBilletera.setText( String.valueOf(jugador.billetera));
                
            }break; 
           
        }
        
        

        
    }//GEN-LAST:event_botonLanzarMouseClicked

    private void textoValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoValor1ActionPerformed

    private void textoBilleteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBilleteraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoBilleteraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLanzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField textoApuesta;
    private javax.swing.JTextField textoBilletera;
    private javax.swing.JTextField textoMensaje;
    private javax.swing.JTextField textoValor1;
    private javax.swing.JTextField textoValor2;
    // End of variables declaration//GEN-END:variables
}
